export * from "./auth.interface";
export * from "./blog.interface";
export * from "./cart.interface";
export * from "./comment.interface";
export * from "./feedback.interface";
export * from "./price.interface";
export * from "./product.interface";
export * from "./response.interface";
export * from "./root.interface";
export * from "./stock.interface";
export * from "./tag.interface";
export * from "./order.interface";
export * from "./company.interface";
export * from "./uploadcv.interface"
export * from "./revaluate.interface";
