export const academicDegreeOpt = [
    { value: "Cử nhân", label: "Cử nhân" },
    { value: "Thạc sĩ", label: "Thạc sĩ" },
    { value: "Tiến sĩ", label: "Tiến sĩ" },
    { value: "Khác", label: "Khác" },
]

export const majorOpt = [
    { value: "Khoa học máy tính", label: "Khoa học máy tính" },
    { value: "Kinh doanh", label: "Kinh doanh" },
    { value: "Y học", label: "Y học" },
    { value: "Nghệ thuật", label: "Nghệ thuật" },
    { value: "Kỹ thuật điện tử", label: "Kỹ thuật điện tử" },
    { value: "Ngôn ngữ học", label: "Ngôn ngữ học" },
    { value: "Văn hóa học", label: "Văn hóa học" },
    { value: "Khoa học xã hội", label: "Khoa học xã hội" },
    { value: "Hóa học", label: "Hóa học" },
    { value: "Vật lý", label: "Vật lý" },
    { value: "Toán học", label: "Toán học" },
    { value: "Quản trị công nghiệp", label: "Quản trị công nghiệp" },
    { value: "Nghệ thuật kịch", label: "Nghệ thuật kịch" },
    { value: "Ngôn ngữ nước ngoài", label: "Ngôn ngữ nước ngoài" },
    { value: "Du lịch và khách sạn", label: "Du lịch và khách sạn" },
    { value: "Sinh học", label: "Sinh học" },
    { value: "Kỹ thuật môi trường", label: "Kỹ thuật môi trường" },
    { value: "Tâm lý học", label: "Tâm lý học" },
    { value: "Luật", label: "Luật" },
    { value: "Kỹ thuật cơ khí", label: "Kỹ thuật cơ khí" },
    { value: "Khác", label: "Khác" },
];
