// "use client";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import classNames from "classnames";
import "@/styles/_global.scss";
import { CssBaseline, StyledEngineProvider, createTheme } from "@mui/material";
import ThemeRegistry from "./ThemeRegistry";
import NextTopLoader from "nextjs-toploader";
import Header from "@/common/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["vietnamese"],
  preload: true,
  fallback: ["Quicksand"],
});

export default function RootLayout({ children, params, ...props }: any) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
        <CssBaseline />
        <body className={classNames(montserrat.className)}>
          <NextTopLoader />
          <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
        </body>
      </StyledEngineProvider>
    </html>
  );
}
