import { SelectOption } from "@/common/components/control/select/types";

export const countryOpt: readonly SelectOption[] = [
    { value: "USA", label: "United States" },
    { value: "CAN", label: "Canada" },
    { value: "GBR", label: "United Kingdom" },
    { value: "AUS", label: "Australia" },
    { value: "GER", label: "Germany" },
    { value: "FRA", label: "France" },
    { value: "JPN", label: "Japan" },
    { value: "BRA", label: "Brazil" },
    { value: "IND", label: "India" },
    { value: "CHN", label: "China" },
    { value: "MEX", label: "Mexico" },
    { value: "RUS", label: "Russia" },
    { value: "ZAF", label: "South Africa" },
    { value: "NZL", label: "New Zealand" },
    { value: "SWE", label: "Sweden" },
    { value: "NOR", label: "Norway" },
    { value: "DEN", label: "Denmark" },
    { value: "TUR", label: "Turkey" },
    { value: "UAE", label: "United Arab Emirates" },
    { value: "VNM", label: "Vietnam" },
    { value: "ARG", label: "Argentina" },
    { value: "AUT", label: "Austria" },
    { value: "BEL", label: "Belgium" },
    { value: "CHL", label: "Chile" },
    { value: "COL", label: "Colombia" },
    { value: "CZE", label: "Czech Republic" },
    { value: "EGY", label: "Egypt" },
    { value: "FIN", label: "Finland" },
    { value: "GRC", label: "Greece" },
    { value: "HUN", label: "Hungary" },
    { value: "IDN", label: "Indonesia" },
    { value: "IRL", label: "Ireland" },
    { value: "ISR", label: "Israel" },
    { value: "ITA", label: "Italy" },
    { value: "KOR", label: "South Korea" },
    { value: "MYS", label: "Malaysia" },
    { value: "NLD", label: "Netherlands" },
    { value: "PHL", label: "Philippines" },
    { value: "POL", label: "Poland" },
    { value: "PRT", label: "Portugal" },
    { value: "SAU", label: "Saudi Arabia" },
    { value: "SGP", label: "Singapore" },
    { value: "ESP", label: "Spain" },
    { value: "CHE", label: "Switzerland" },
    { value: "THA", label: "Thailand" },
    { value: "UKR", label: "Ukraine" },
    { value: "URY", label: "Uruguay" },
    { value: "VEN", label: "Venezuela" },
    { value: "Other", label: "Other" },
];

export const cityOpt: readonly SelectOption[] = [
    { value: "Hà Nội", label: "Hà Nội" },
    { value: "Hồ Chí Minh", label: "Hồ Chí Minh" },
    { value: "Huế", label: "Huế" },
    { value: "Đà Nẵng", label: "Đà Nẵng" },
    { value: "Nha Trang", label: "Nha Trang" },
    { value: "Hải Phòng", label: "Hải Phòng" },
    { value: "Vinh", label: "Vinh" },
    { value: "Hà Tĩnh", label: "Hà Tĩnh" },
    { value: "Cần Thơ", label: "Cần Thơ" },
    { value: "Quy Nhơn", label: "Quy Nhơn" },
    { value: "Vũng Tàu", label: "Vũng Tàu" },
    { value: "Pleiku", label: "Pleiku" },
    { value: "Đà Lạt", label: "Đà Lạt" },
    { value: "Buôn Ma Thuột", label: "Buôn Ma Thuột" },
    { value: "Tuy Hòa", label: "Tuy Hòa" },
    { value: "Cam Ranh", label: "Cam Ranh" },
    { value: "Điện Biên Phủ", label: "Điện Biên Phủ" },
    { value: "Phan Thiết", label: "Phan Thiết" },
    { value: "Cà Mau", label: "Cà Mau" },
    { value: "Thái Nguyên", label: "Thái Nguyên" },
    { value: "Other", label: "Other" },
];

