import { SelectOption } from "@/common/components/control/select/types";

export const currencyUnitOpt: readonly SelectOption[] = [
    { value: "USD", label: "USD" },
    { value: "EUR", label: "EUR" },
    { value: "GBP", label: "GBP" },
    { value: "JPY", label: "JPY" },
    { value: "AUD", label: "AUD" },
    { value: "CAD", label: "CAD" },
    { value: "CHF", label: "CHF" },
    { value: "CNY", label: "CNY" },
    { value: "INR", label: "INR" },
    { value: "SGD", label: "SGD" },
    { value: "MXN", label: "MXN" },
    { value: "BRL", label: "BRL" },
    { value: "RUB", label: "RUB" },
    { value: "ZAR", label: "ZAR" },
    { value: "NZD", label: "NZD" },
    { value: "SEK", label: "SEK" },
    { value: "NOK", label: "NOK" },
    { value: "DKK", label: "DKK" },
    { value: "TRY", label: "TRY" },
    { value: "AED", label: "AED" },
    { value: "VND", label: "VND" },
    { value: "Other", label: "Other" },
];
