export const languageCertificationOptions = [
    { value: 'toefl_ibt', label: 'TOEFL iBT (Test of English as a Foreign Language - Internet-based Test)' },
    { value: 'toefl_pbt', label: 'TOEFL PBT (Test of English as a Foreign Language - Paper-based Test)' },
    { value: 'ielts', label: 'IELTS (International English Language Testing System)' },
    { value: 'delf', label: 'DELF (Diplôme d\'Études en Langue Française)' },
    { value: 'dalf', label: 'DALF (Diplôme Approfondi de Langue Française)' },
    { value: 'hsk', label: 'HSK (Hanyu Shuiping Kaoshi)' },
    { value: 'celpe_br', label: 'CELPE-Bras (Certificate of Proficiency in Portuguese for Foreigners)' },
    { value: 'jlpt', label: 'JLPT (Japanese Language Proficiency Test)' },
    { value: 'dele', label: 'DELE (Diplomas de Español como Lengua Extranjera)' },
    { value: 'pte_academic', label: 'PTE Academic (Pearson Test of English Academic)' },
    { value: 'cils', label: 'CILS (Certificazione di Italiano come Lingua Straniera)' },
    { value: 'tef', label: 'TEF (Test d\'Évaluation de Français)' },
    { value: 'delf_dalf_arabe', label: 'DELF-DALF en langue arabe' },
    { value: 'korean_language_exam', label: 'Korean Language Proficiency Test (KLPT)' },
    { value: 'celt', label: 'Certificate in English Language Teaching (CELTA)' },
    { value: 'tesol', label: 'TESOL (Teaching English to Speakers of Other Languages)' },
  ];

 export const languageOptions = [
    { value: 'english', label: 'English' },
    { value: 'spanish', label: 'Spanish' },
    { value: 'french', label: 'French' },
    { value: 'german', label: 'German' },
    { value: 'chinese', label: 'Chinese' },
    { value: 'japanese', label: 'Japanese' },
    { value: 'korean', label: 'Korean' },
    { value: 'arabic', label: 'Arabic' },
    { value: 'portuguese', label: 'Portuguese' },
    { value: 'italian', label: 'Italian' },
    { value: 'russian', label: 'Russian' },
    { value: 'dutch', label: 'Dutch' },
    { value: 'swedish', label: 'Swedish' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'vietnamese', label: 'Vietnamese' },
    { value: 'thai', label: 'Thai' },
    { value: 'indonesian', label: 'Indonesian' },
    { value: 'malay', label: 'Malay' },
    { value: 'greek', label: 'Greek' },
    { value: 'turkish', label: 'Turkish' },
    { value: 'hebrew', label: 'Hebrew' },
    { value: 'persian', label: 'Persian' },
    { value: 'urdu', label: 'Urdu' },
    { value: 'swahili', label: 'Swahili' },
    { value: 'tagalog', label: 'Tagalog' },
    { value: 'bengali', label: 'Bengali' },
    { value: 'punjabi', label: 'Punjabi' },
  ];
  