export const jobTitleOpt = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "DevOps",
  "QA",
  "Tester",
  "Technical Leader",
  "Technical Manager",
  "Project Manager",
  "Scrum Master",
  "Product Manager",
  "Business Analyst",
  "System Analyst",
  "Architect",
  "UI/UX Designer",
  "Mobile Developer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Data Architect",
  "Data Warehouse",
  "Data Mining",
  "Data Visualization",
  "Big Data",
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "NLP",
  "Blockchain",
  "Cyber Security",
  "Embedded",
  "Fresher",
  "Internship",
  "Other",
];

export const departmentOpt = [
  "IT",
  "Business",
  "Marketing",
  "HR",
  "Finance",
  "Other",
];

export const jobLevelOpt = [
  "Internship",
  "Fresher",
  "Junior",
  "Senior",
  "Team Leader",
  "Manager",
  "Director",
  "Other",
];

export const responsibilityOpt = [
  "Develop and maintain web applications",
  "Develop and maintain mobile applications",
  "Develop and maintain APIs",
  "Develop and maintain web services",
  "Develop and maintain microservices",
  "Develop and maintain chatbots",
  "Develop and maintain AI models",
  "Develop and maintain data pipelines",
  "Develop and maintain data visualization",
  "Develop and maintain data warehouse",
  "Develop and maintain data mining",
  "Develop and maintain data analytics",
  "Develop and maintain data science",
  "Develop and maintain blockchain",
  "Develop and maintain cyber security",
  "Develop and maintain embedded systems",
  "Develop and maintain other systems",
  "Other",
];
